fix: formatting and find syntax in jenkins (esc for Groovy)

diff --git a/extras/jenkins/Minikube/Jenkinsfile b/extras/jenkins/Minikube/Jenkinsfile
--- a/extras/jenkins/Minikube/Jenkinsfile
+++ b/extras/jenkins/Minikube/Jenkinsfile
@@ -71,7 +71,7 @@ pipeline {
             DEBIAN_FRONTEND=noninteractive apt -y install figlet openjdk-11-jdk make docker.io conntrack expect
             # Make sure our kubeconfig dir exists…
             mkdir $HOME/.kube || true
-            '''
+             '''
       }
     }
 
@@ -79,26 +79,17 @@ pipeline {
       steps {
 
         /*
-         * Run a find and check for any stacks that currently exist with our generated stack name; this should not
-         * happen in normal operation, but could potentially happen if things break so better safe than sorry.
+         * This is currently empty since we are building a new executor for each run. However, maintaining
+         * here for anyone who wants to add cleanup steps for their environment
          *
-         * This function also tries to remove both K3S and Microk8s if they are found on the host; this is because we
-         * will be installing Microk8s and we want to both make sure we are removing any previous installations as well as
-         * ensuring this Jenkins Agent does not already have a Microk8s installation on it.
+         * Other cleanup related functions can be placed here as well.
          */
 
-          sh '''
-            # Reset our K3S Environment
-            /usr/local/bin/k3s-killall.sh || true
-            /usr/local/bin/k3s-uninstall.sh || true
-            # Reset our Microk8s Environment; true if it’s not there
-            microk8s reset --destroy-storage || true
-            # True if it’s not there…
-            snap remove microk8s || true
-            # Clean up the Pulumi stack if it exists for our run - which it shouldn\'t, but you never know.
-            find  $WORKSPACE -mindepth 2 -maxdepth 7 -type f -name Pulumi.yaml -execdir $WORKSPACE/pulumi/python/venv/bin/pulumi stack rm marajenk${BUILD_NUMBER}  --force --yes  \\;
-            '''
-      }
+        sh '''
+          # Just return...
+          true
+           '''
+       }
     }
 
     stage('Minikube Setup') {
@@ -166,20 +157,20 @@ _EOF_
          */
 
           sh '''
-            echo "PULUMI_STACK=marajenk${BUILD_NUMBER}" > $WORKSPACE/config/pulumi/environment
-            $WORKSPACE/pulumi/python/venv/bin/pulumi stack select --create marajenk${BUILD_NUMBER} -C pulumi/python/config
-            $WORKSPACE/pulumi/python/venv/bin/pulumi stack select --create marajenk${BUILD_NUMBER} -C pulumi/python/kubernetes/applications/sirius
-            $WORKSPACE/pulumi/python/venv/bin/pulumi config set certmgr:helm_timeout "600" -C pulumi/python/config -s marajenk${BUILD_NUMBER}
-            $WORKSPACE/pulumi/python/venv/bin/pulumi config set kic-helm:fqdn "marajenks${BUILD_NUMBER}.zathras.io" -C pulumi/python/config -s marajenk${BUILD_NUMBER}
-            $WORKSPACE/pulumi/python/venv/bin/pulumi config set kic-helm:helm_timeout "600" -C pulumi/python/config -s marajenk${BUILD_NUMBER}
-            $WORKSPACE/pulumi/python/venv/bin/pulumi config set kubernetes:cluster_name "microk8s-cluster" -C pulumi/python/config -s marajenk${BUILD_NUMBER}
-            $WORKSPACE/pulumi/python/venv/bin/pulumi config set kubernetes:infra_type "kubeconfig" -C pulumi/python/config -s marajenk${BUILD_NUMBER}
-            $WORKSPACE/pulumi/python/venv/bin/pulumi config set kubernetes:kubeconfig "$HOME/.kube/config" -C pulumi/python/config -s marajenk${BUILD_NUMBER}
-            $WORKSPACE/pulumi/python/venv/bin/pulumi config set logagent:helm_timeout "600" -C pulumi/python/config -s marajenk${BUILD_NUMBER}
-            $WORKSPACE/pulumi/python/venv/bin/pulumi config set logstore:helm_timeout "600" -C pulumi/python/config -s marajenk${BUILD_NUMBER}
-            $WORKSPACE/pulumi/python/venv/bin/pulumi config set prometheus:adminpass "password" -C pulumi/python/config -s marajenk${BUILD_NUMBER}
-            $WORKSPACE/pulumi/python/venv/bin/pulumi config set prometheus:helm_timeout "600" -C pulumi/python/config -s marajenk${BUILD_NUMBER}
-            $WORKSPACE/pulumi/python/venv/bin/pulumi config set prometheus:helm_timeout "600" -C pulumi/python/config -s marajenk${BUILD_NUMBER}
+            echo "PULUMI_STACK=marajenkmkube${BUILD_NUMBER}" > $WORKSPACE/config/pulumi/environment
+            $WORKSPACE/pulumi/python/venv/bin/pulumi stack select --create marajenkmkube${BUILD_NUMBER} -C pulumi/python/config
+            $WORKSPACE/pulumi/python/venv/bin/pulumi stack select --create marajenkmkube${BUILD_NUMBER} -C pulumi/python/kubernetes/applications/sirius
+            $WORKSPACE/pulumi/python/venv/bin/pulumi config set certmgr:helm_timeout "600" -C pulumi/python/config -s marajenkmkube${BUILD_NUMBER}
+            $WORKSPACE/pulumi/python/venv/bin/pulumi config set kic-helm:fqdn "marajenkmkubes${BUILD_NUMBER}.zathras.io" -C pulumi/python/config -s marajenkmkube${BUILD_NUMBER}
+            $WORKSPACE/pulumi/python/venv/bin/pulumi config set kic-helm:helm_timeout "600" -C pulumi/python/config -s marajenkmkube${BUILD_NUMBER}
+            $WORKSPACE/pulumi/python/venv/bin/pulumi config set kubernetes:cluster_name "microk8s-cluster" -C pulumi/python/config -s marajenkmkube${BUILD_NUMBER}
+            $WORKSPACE/pulumi/python/venv/bin/pulumi config set kubernetes:infra_type "kubeconfig" -C pulumi/python/config -s marajenkmkube${BUILD_NUMBER}
+            $WORKSPACE/pulumi/python/venv/bin/pulumi config set kubernetes:kubeconfig "$HOME/.kube/config" -C pulumi/python/config -s marajenkmkube${BUILD_NUMBER}
+            $WORKSPACE/pulumi/python/venv/bin/pulumi config set logagent:helm_timeout "600" -C pulumi/python/config -s marajenkmkube${BUILD_NUMBER}
+            $WORKSPACE/pulumi/python/venv/bin/pulumi config set logstore:helm_timeout "600" -C pulumi/python/config -s marajenkmkube${BUILD_NUMBER}
+            $WORKSPACE/pulumi/python/venv/bin/pulumi config set prometheus:adminpass "password" -C pulumi/python/config -s marajenkmkube${BUILD_NUMBER}
+            $WORKSPACE/pulumi/python/venv/bin/pulumi config set prometheus:helm_timeout "600" -C pulumi/python/config -s marajenkmkube${BUILD_NUMBER}
+            $WORKSPACE/pulumi/python/venv/bin/pulumi config set prometheus:helm_timeout "600" -C pulumi/python/config -s marajenkmkube${BUILD_NUMBER}
             '''
       }
     }
@@ -216,7 +207,7 @@ _EOF_
             microk8s reset --destroy-storage || true
             # True if it’s not there…
             snap remove microk8s || true
-            find . -mindepth 2 -maxdepth 6 -type f -name Pulumi.yaml -execdir $WORKSPACE/pulumi/python/venv/bin/pulumi stack rm marajenk${BUILD_NUMBER} --force --yes \\;
+            find . -mindepth 2 -maxdepth 6 -type f -name Pulumi.yaml -execdir $WORKSPACE/pulumi/python/venv/bin/pulumi stack rm marajenkmkube${BUILD_NUMBER} --force --yes \\;
             # This is a hack to allow additional commands to be issued following cleanup. This is needed because the VMs
             # that currently run as agents for K3S and Microk8s deployments need to be rebooted following some number of
             # runs due to zombie processes and other issues. Long term we want to deploy these VM's via IaaC so the only
@@ -240,17 +231,13 @@ _EOF_
            */
 
         sh '''
-            # Destroy our partial build...
-            $WORKSPACE/bin/destroy.sh || true
-            # Reset our Microk8s Environment; true if it’s not there
-            microk8s reset --destroy-storage || true
-            # True if it’s not there…
-            snap remove microk8s || true
-            # True if it's not there
-            minikube delete || true
-            # Clean up the Pulumi stack if it exists for our run - which it shouldn\'t, but you never know.
-            find  $WORKSPACE -mindepth 2 -maxdepth 7 -type f -name Pulumi.yaml -execdir $WORKSPACE/pulumi/python/venv/bin/pulumi stack rm marajenk${BUILD_NUMBER}  --force --yes  \;
-            '''
+           # Destroy our partial build...
+           $WORKSPACE/bin/destroy.sh || true
+           # True if it's not there
+           minikube delete || true
+           # Clean up the Pulumi stack if it exists for our run - which it shouldn\'t, but you never know.
+           find  $WORKSPACE -mindepth 2 -maxdepth 7 -type f -name Pulumi.yaml -execdir $WORKSPACE/pulumi/python/venv/bin/pulumi stack rm marajenkmkube${BUILD_NUMBER}  --force --yes \\;
+           '''
     }
   }
 }
